Traceback (most recent call last):
  File "c:\users\parth\.conda\envs\py37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\parth\.conda\envs\py37\lib\site-packages\nbclient\client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\parth\.conda\envs\py37\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\parth\.conda\envs\py37\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\parth\.conda\envs\py37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\parth\.conda\envs\py37\lib\site-packages\nbclient\client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\parth\.conda\envs\py37\lib\site-packages\nbclient\client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\parth\.conda\envs\py37\lib\site-packages\nbclient\client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from scipy.stats import beta
import plotly.graph_objs as go
import numpy as np
from ipywidgets import interact

# fig, ax = plt.subplots(1, 1)
# a, b = 2.31, 0.627
# x = np.linspace(beta.ppf(0.01, a, b),
#                 beta.ppf(0.99, a, b), 100)
# ax.plot(x, beta.pdf(x, a, b),
#        'r-', lw=5, alpha=0.6, label='beta pdf')
# plt.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m<ipython-input-1-c503242c75b4>[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mfrom[0m [0mscipy[0m[1;33m.[0m[0mstats[0m [1;32mimport[0m [0mbeta[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;32mimport[0m [0mplotly[0m[1;33m.[0m[0mgraph_objs[0m [1;32mas[0m [0mgo[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [1;32mimport[0m [0mnumpy[0m [1;32mas[0m [0mnp[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [1;32mfrom[0m [0mipywidgets[0m [1;32mimport[0m [0minteract[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'scipy'
ModuleNotFoundError: No module named 'scipy'

